// Centralized dark "slate/zinc" theme tokens, used as plain JS style objects
// so no Tailwind / CSS framework setup is required.

export const colors = {
  bg: "#0b0d10",
  panelBg: "#111317",
  panelBgAlt: "#15181d",
  border: "#23262c",
  borderLight: "#2a2e35",
  text: "#e6e7ea",
  textDim: "#9aa0aa",
  textFaint: "#5b6068",
  accent: "#7c9cff",
  accentDim: "#3d4a73",
  userBubble: "#1d2b53",
  botBubble: "#16181c",
  success: "#3ddc97",
  codeBg: "#0d0f12",
};

export const styles = {
  app: {
    display: "flex",
    width: "100vw",
    height: "100vh",
    background: colors.bg,
    color: colors.text,
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    overflow: "hidden",
  },

  // ----- Chat column -----
  chatColumn: {
    flex: "1 1 55%",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    borderRight: `1px solid ${colors.border}`,
  },
  chatHeader: {
    padding: "14px 20px",
    borderBottom: `1px solid ${colors.border}`,
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: 0.2,
    color: colors.text,
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: colors.panelBg,
  },
  chatMessages: {
    flex: 1,
    overflowY: "auto",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  bubbleRow: (role) => ({
    display: "flex",
    justifyContent: role === "user" ? "flex-end" : "flex-start",
  }),
  bubble: (role) => ({
    maxWidth: "82%",
    padding: "10px 14px",
    borderRadius: 14,
    fontSize: 14.5,
    lineHeight: 1.55,
    background: role === "user" ? colors.userBubble : colors.botBubble,
    border: `1px solid ${role === "user" ? colors.accentDim : colors.border}`,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  }),
  chatInputBar: {
    display: "flex",
    gap: 10,
    padding: "14px 16px",
    borderTop: `1px solid ${colors.border}`,
    background: colors.panelBg,
  },
  textarea: {
    flex: 1,
    resize: "none",
    background: colors.panelBgAlt,
    color: colors.text,
    border: `1px solid ${colors.borderLight}`,
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
    fontFamily: "inherit",
    outline: "none",
    maxHeight: 140,
  },
  sendBtn: (disabled) => ({
    background: disabled ? colors.accentDim : colors.accent,
    color: disabled ? colors.textFaint : "#0b0d10",
    border: "none",
    borderRadius: 10,
    padding: "0 18px",
    fontWeight: 600,
    fontSize: 14,
    cursor: disabled ? "not-allowed" : "pointer",
  }),

  // ----- Artifact column -----
  artifactColumn: {
    flex: "1 1 45%",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    background: colors.panelBg,
  },
  artifactHeader: {
    padding: "14px 20px",
    borderBottom: `1px solid ${colors.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  artifactTabs: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    padding: "8px 12px",
    borderBottom: `1px solid ${colors.border}`,
  },
  tab: (active) => ({
    padding: "6px 12px",
    borderRadius: 8,
    fontSize: 12.5,
    whiteSpace: "nowrap",
    cursor: "pointer",
    background: active ? colors.accentDim : "transparent",
    color: active ? colors.text : colors.textDim,
    border: `1px solid ${active ? colors.accent : "transparent"}`,
  }),
  artifactBody: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  codeBlockWrap: {
    flex: 1,
    overflow: "auto",
    background: colors.codeBg,
    margin: "0 16px 16px 16px",
    borderRadius: 12,
    border: `1px solid ${colors.border}`,
  },
  codeBlockHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    borderBottom: `1px solid ${colors.border}`,
    position: "sticky",
    top: 0,
    background: colors.codeBg,
  },
  filename: {
    fontSize: 13,
    fontFamily: "'Fira Code', monospace",
    color: colors.accent,
  },
  pre: {
    margin: 0,
    padding: "16px",
    fontSize: 13,
    lineHeight: 1.6,
    fontFamily: "'Fira Code', 'Cascadia Code', monospace",
    color: "#d4d8dd",
    whiteSpace: "pre",
  },
  actionBtnRow: {
    display: "flex",
    gap: 8,
  },
  iconBtn: (variant = "default") => ({
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    padding: "6px 10px",
    borderRadius: 8,
    border: `1px solid ${colors.borderLight}`,
    background: variant === "primary" ? colors.accent : "transparent",
    color: variant === "primary" ? "#0b0d10" : colors.textDim,
    cursor: "pointer",
    fontWeight: 500,
  }),
  emptyState: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: colors.textFaint,
    fontSize: 13.5,
    textAlign: "center",
    padding: 30,
    gap: 8,
  },
  statusDot: (streaming) => ({
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: streaming ? colors.success : colors.textFaint,
  }),

  modelSelect: {
    background: colors.panelBgAlt,
    color: colors.text,
    border: `1px solid ${colors.borderLight}`,
    borderRadius: 8,
    padding: "5px 8px",
    fontSize: 12.5,
    outline: "none",
    cursor: "pointer",
    maxWidth: 220,
  },
  modelNote: {
    fontSize: 11.5,
    color: colors.textFaint,
    marginLeft: 2,
  },
};
